use cookbook_core::{
    Plan, PlanError, PlanReader, PlanResult, Recipe, RecipeError, RecipeReader, RecipeResult,
};
use std::collections::HashMap;
use std::sync::OnceLock;
use uuid::Uuid;

/// Embedded recipe store that includes all recipe markdown files at compile time.
/// This is suitable for WASM/web targets where filesystem access is not available.
#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
pub struct EmbeddedRecipeStore {
    recipes: HashMap<String, Recipe>,
}

static EMBEDDED_STORE: OnceLock<EmbeddedRecipeStore> = OnceLock::new();

#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
impl EmbeddedRecipeStore {
    /// Get the global embedded recipe store instance
    pub fn global() -> &'static EmbeddedRecipeStore {
        EMBEDDED_STORE.get_or_init(|| {
            let mut store = EmbeddedRecipeStore {
                recipes: HashMap::new(),
            };
            store.load_embedded_recipes();
            store
        })
    }

    /// Load all embedded recipes at initialization
    fn load_embedded_recipes(&mut self) {
        // Recipe files are auto-generated by build.rs at compile time
        // This prevents issues when files are added, removed, or renamed
        let recipe_files: Vec<(u32, &str)> =
            include!(concat!(env!("OUT_DIR"), "/embedded_recipes.rs"));

        for (day, content) in recipe_files {
            match Self::parse_recipe_markdown(content, day) {
                Ok(recipe) => {
                    self.recipes.insert(recipe.id.clone(), recipe);
                }
                Err(e) => {
                    // Log parsing failures to help with debugging
                    tracing::warn!(
                        day = day,
                        error = %e,
                        "Failed to parse recipe markdown for day {}",
                        day
                    );
                }
            }
        }

        // Verify we loaded all 365 recipes
        assert_eq!(
            self.recipes.len(),
            365,
            "Expected to load 365 recipes but loaded {}. Check that all recipe files exist and parse correctly.",
            self.recipes.len()
        );
    }

    /// Parses recipe data from markdown content
    fn parse_recipe_markdown(content: &str, day: u32) -> RecipeResult<Recipe> {
        let id = format!("day-{}", day);

        // Parse title from first heading or use day as title
        let title = Self::extract_title(content).unwrap_or_else(|| format!("Day {} Recipe", day));

        // Try to extract UUID from frontmatter, generate a new one if not found or invalid
        let uuid = Self::extract_uuid(content).unwrap_or_else(Uuid::new_v4);

        // Create recipe with extracted or generated UUID
        let mut recipe = Recipe::new_with_uuid(id, uuid, title);

        // Parse optional fields from markdown
        recipe.description = Self::extract_description(content);
        recipe.ingredients = Self::extract_ingredients(content);
        recipe.instructions = Self::extract_instructions(content);
        recipe.prep_time_minutes = Self::extract_prep_time(content);
        recipe.cook_time_minutes = Self::extract_cook_time(content);
        recipe.servings = Self::extract_servings(content);
        recipe.tags = Self::extract_tags(content);

        Ok(recipe)
    }

    /// Extracts the title from markdown (first # heading)
    fn extract_title(content: &str) -> Option<String> {
        for line in content.lines() {
            let trimmed = line.trim();
            if let Some(title) = trimmed.strip_prefix("# ") {
                return Some(title.trim().to_string());
            }
        }
        None
    }

    /// Extracts description (text before first section)
    fn extract_description(content: &str) -> Option<String> {
        let mut desc_lines = Vec::new();
        let mut in_description = false;

        for line in content.lines() {
            let trimmed = line.trim();

            // Skip title
            if trimmed.starts_with("# ") {
                in_description = true;
                continue;
            }

            // Stop at first section heading
            if trimmed.starts_with("## ") {
                break;
            }

            if in_description && !trimmed.is_empty() {
                desc_lines.push(trimmed.to_string());
            }
        }

        if desc_lines.is_empty() {
            None
        } else {
            Some(desc_lines.join(" "))
        }
    }

    /// Extracts ingredients from ## Ingredients section
    fn extract_ingredients(content: &str) -> Vec<String> {
        Self::extract_list_section(content, "## Ingredients")
    }

    /// Extracts instructions from ## Instructions section
    fn extract_instructions(content: &str) -> Vec<String> {
        Self::extract_list_section(content, "## Instructions")
    }

    /// Extracts a list from a markdown section
    fn extract_list_section(content: &str, section_header: &str) -> Vec<String> {
        let mut items = Vec::new();
        let mut in_section = false;

        for line in content.lines() {
            let trimmed = line.trim();

            if trimmed == section_header {
                in_section = true;
                continue;
            }

            // Stop at next section
            if in_section && trimmed.starts_with("## ") {
                break;
            }

            if in_section {
                // Handle both - and numbered lists
                if let Some(item) = trimmed.strip_prefix("- ") {
                    items.push(item.trim().to_string());
                } else if let Some(pos) = trimmed.find(". ") {
                    // Check if it's a numbered list (e.g., "1. ")
                    if trimmed[..pos].chars().all(|c| c.is_ascii_digit()) {
                        items.push(trimmed[pos + 2..].trim().to_string());
                    }
                }
            }
        }

        items
    }

    /// Extracts prep time from metadata
    fn extract_prep_time(content: &str) -> Option<u32> {
        Self::extract_time_field(content, "Prep Time:")
    }

    /// Extracts cook time from metadata
    fn extract_cook_time(content: &str) -> Option<u32> {
        Self::extract_time_field(content, "Cook Time:")
    }

    /// Extracts a time field in minutes
    /// Expected format: "X minutes" or "X" where X is a positive integer
    fn extract_time_field(content: &str, field: &str) -> Option<u32> {
        for line in content.lines() {
            if let Some(value) = line.strip_prefix(field) {
                let value = value.trim();
                // Parse "X minutes" or just "X"
                let num_str = value.split_whitespace().next()?;
                return num_str.parse::<u32>().ok();
            }
        }
        None
    }

    /// Extracts servings from metadata
    fn extract_servings(content: &str) -> Option<u32> {
        for line in content.lines() {
            if let Some(value) = line.strip_prefix("Servings:") {
                let value = value.trim();
                let num_str = value.split_whitespace().next()?;
                return num_str.parse::<u32>().ok();
            }
        }
        None
    }

    /// Extracts tags from metadata
    fn extract_tags(content: &str) -> Vec<String> {
        for line in content.lines() {
            if let Some(value) = line.strip_prefix("Tags:") {
                return value
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
        }
        Vec::new()
    }

    /// Extracts UUID from metadata
    /// Returns None if no UUID field is found or if the UUID is invalid
    fn extract_uuid(content: &str) -> Option<Uuid> {
        for line in content.lines() {
            if let Some(value) = line.strip_prefix("UUID:") {
                let uuid_str = value.trim();
                // Try to parse the UUID
                if let Ok(uuid) = Uuid::parse_str(uuid_str) {
                    return Some(uuid);
                }
                // If parsing fails, return None (caller will generate a new UUID)
                return None;
            }
        }
        None
    }
}

#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
impl RecipeReader for EmbeddedRecipeStore {
    fn get_by_id(&self, id: &str) -> RecipeResult<Recipe> {
        // Try to parse as UUID first
        if let Ok(uuid) = Uuid::parse_str(id) {
            return self.get_by_uuid(&uuid);
        }

        // Fall back to legacy ID lookup
        self.recipes
            .get(id)
            .cloned()
            .ok_or_else(|| RecipeError::NotFound(format!("Recipe with id '{}' not found", id)))
    }

    fn get_by_uuid(&self, uuid: &Uuid) -> RecipeResult<Recipe> {
        self.recipes
            .values()
            .find(|r| r.uuid == *uuid)
            .cloned()
            .ok_or_else(|| RecipeError::NotFound(format!("Recipe with uuid '{}' not found", uuid)))
    }

    #[allow(deprecated)]
    fn get_all(&self) -> RecipeResult<Vec<Recipe>> {
        Ok(self.recipes.values().cloned().collect())
    }

    fn exists(&self, id: &str) -> bool {
        self.recipes.contains_key(id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_embedded_store_loads_recipes() {
        let store = EmbeddedRecipeStore::global();
        let recipes = store.get_all().unwrap();
        assert_eq!(recipes.len(), 365, "Should load all 365 recipes");
    }

    #[test]
    fn test_recipe_has_content() {
        let store = EmbeddedRecipeStore::global();
        let recipe = store.get_by_id("day-1").unwrap();

        // Verify recipe has parsed content
        assert!(!recipe.title.is_empty());
        assert!(recipe.description.is_some());
        assert!(!recipe.ingredients.is_empty());
        assert!(!recipe.instructions.is_empty());
        assert!(recipe.prep_time_minutes.is_some());
        assert!(recipe.cook_time_minutes.is_some());
        assert!(recipe.servings.is_some());
    }

    #[test]
    fn test_global_instance_is_singleton() {
        let store1 = EmbeddedRecipeStore::global();
        let store2 = EmbeddedRecipeStore::global();

        // Both should point to the same instance
        assert_eq!(
            store1 as *const _, store2 as *const _,
            "Global instance should be a singleton"
        );
    }
}

/// Embedded plan store that includes all plan markdown files at compile time.
/// This is suitable for WASM/web targets where filesystem access is not available.
#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
pub struct EmbeddedPlanStore {
    plans: HashMap<u32, Plan>,
}

static EMBEDDED_PLAN_STORE: OnceLock<EmbeddedPlanStore> = OnceLock::new();

#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
impl EmbeddedPlanStore {
    /// Get the global embedded plan store instance
    pub fn global() -> &'static EmbeddedPlanStore {
        EMBEDDED_PLAN_STORE.get_or_init(|| {
            let mut store = EmbeddedPlanStore {
                plans: HashMap::new(),
            };
            store.load_embedded_plans();
            store
        })
    }

    /// Load all embedded plans at initialization
    fn load_embedded_plans(&mut self) {
        // Plan files are auto-generated by build.rs at compile time
        let plan_files: Vec<(u32, &str)> = include!(concat!(env!("OUT_DIR"), "/embedded_plans.rs"));

        for (week, content) in plan_files {
            match Self::parse_plan_markdown(content, week) {
                Ok(plan) => {
                    self.plans.insert(plan.week, plan);
                }
                Err(e) => {
                    // Log parsing failures to help with debugging
                    tracing::warn!(
                        week = week,
                        error = %e,
                        "Failed to parse plan markdown for week {}",
                        week
                    );
                }
            }
        }

        // Verify we loaded plans (should be 52-53 depending on year)
        // Some years have 53 ISO weeks (e.g., 2020, 2026), others have 52 (e.g., 2024)
        assert!(
            self.plans.len() >= 52 && self.plans.len() <= 53,
            "Expected to load 52-53 plans but loaded {}. Check that plan files exist and parse correctly.",
            self.plans.len()
        );
    }

    /// Parses plan data from markdown content
    fn parse_plan_markdown(content: &str, week: u32) -> PlanResult<Plan> {
        // Extract recipe UUIDs from the markdown content
        // Format: "Recipe UUIDs: uuid1, uuid2, uuid3, ..."
        let recipe_uuids = Self::extract_recipe_uuids(content)?;

        // Validate we have exactly 7 UUIDs
        if recipe_uuids.len() != 7 {
            return Err(PlanError::InvalidData(format!(
                "Plan for week {} must have exactly 7 recipe UUIDs, found {}",
                week,
                recipe_uuids.len()
            )));
        }

        Plan::new_checked(week, recipe_uuids).map_err(|e| {
            PlanError::InvalidData(format!("Failed to create plan for week {}: {}", week, e))
        })
    }

    /// Extracts recipe UUIDs from the markdown content
    fn extract_recipe_uuids(content: &str) -> PlanResult<Vec<Uuid>> {
        // Look for the "Recipe UUIDs: X, Y, Z" line
        for line in content.lines() {
            let trimmed = line.trim();
            if let Some(uuids_str) = trimmed.strip_prefix("Recipe UUIDs:") {
                let uuids: Result<Vec<Uuid>, _> = uuids_str
                    .split(',')
                    .map(|s| {
                        Uuid::parse_str(s.trim())
                            .map_err(|e| PlanError::InvalidData(format!("Invalid UUID: {}", e)))
                    })
                    .collect();

                return uuids;
            }
        }

        Err(PlanError::InvalidData(
            "Could not find 'Recipe UUIDs:' line in plan markdown".to_string(),
        ))
    }
}

#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
impl PlanReader for EmbeddedPlanStore {
    fn get_by_week(&self, week: u32) -> PlanResult<Plan> {
        self.plans
            .get(&week)
            .cloned()
            .ok_or_else(|| PlanError::NotFound(format!("Plan for week {} not found", week)))
    }

    fn get_all(&self) -> PlanResult<Vec<Plan>> {
        let mut plans: Vec<Plan> = self.plans.values().cloned().collect();
        // Sort by week number for consistent ordering
        plans.sort_by_key(|p| p.week);
        Ok(plans)
    }

    fn exists(&self, week: u32) -> bool {
        self.plans.contains_key(&week)
    }
}

#[cfg(test)]
mod plan_tests {
    use super::*;

    #[test]
    fn test_embedded_plan_store_loads_plans() {
        let store = EmbeddedPlanStore::global();
        let plans = store.get_all().unwrap();
        // 2024 has 52 ISO weeks, not 53 (week 53 file has incomplete data)
        assert!(
            plans.len() >= 52,
            "Should load at least 52 plans, got {}",
            plans.len()
        );
    }

    #[test]
    fn test_get_by_week() {
        let store = EmbeddedPlanStore::global();
        let recipe_store = EmbeddedRecipeStore::global();

        // Test week 1
        let plan = store.get_by_week(1).unwrap();
        assert_eq!(plan.week, 1);
        assert_eq!(plan.recipe_uuids.len(), 7);

        // Verify UUIDs match recipes for days 1-7
        for (i, day) in (1..=7).enumerate() {
            let day_id = format!("day-{}", day);
            let recipe = recipe_store.get_by_id(&day_id).unwrap();
            assert_eq!(plan.recipe_uuids[i], recipe.uuid);
        }

        // Test week 2
        let plan = store.get_by_week(2).unwrap();
        assert_eq!(plan.week, 2);
        assert_eq!(plan.recipe_uuids.len(), 7);

        // Verify UUIDs match recipes for days 8-14
        for (i, day) in (8..=14).enumerate() {
            let day_id = format!("day-{}", day);
            let recipe = recipe_store.get_by_id(&day_id).unwrap();
            assert_eq!(plan.recipe_uuids[i], recipe.uuid);
        }

        // Test last valid week (52 for 2024)
        let plan = store.get_by_week(52).unwrap();
        assert_eq!(plan.week, 52);
        assert_eq!(plan.recipe_uuids.len(), 7);
    }

    #[test]
    fn test_invalid_week() {
        let store = EmbeddedPlanStore::global();

        // Week 0 should fail
        assert!(store.get_by_week(0).is_err());

        // Week 54 should fail
        assert!(store.get_by_week(54).is_err());
    }

    #[test]
    fn test_plan_exists() {
        let store = EmbeddedPlanStore::global();

        // All weeks 1-52 should exist (2024 only has 52 weeks)
        for week in 1..=52 {
            assert!(store.exists(week), "Plan for week {} should exist", week);
        }

        // Week 0 and 54 should not exist
        assert!(!store.exists(0));
        assert!(!store.exists(54));
    }

    #[test]
    fn test_get_all_returns_sorted() {
        let store = EmbeddedPlanStore::global();
        let plans = store.get_all().unwrap();

        // Verify plans are sorted by week number
        for i in 0..plans.len() - 1 {
            assert!(
                plans[i].week < plans[i + 1].week,
                "Plans should be sorted by week number"
            );
        }
    }

    #[test]
    fn test_global_plan_instance_is_singleton() {
        let store1 = EmbeddedPlanStore::global();
        let store2 = EmbeddedPlanStore::global();

        // Both should point to the same instance
        assert_eq!(
            store1 as *const _, store2 as *const _,
            "Global instance should be a singleton"
        );
    }

    #[test]
    fn test_parse_plan_markdown() {
        let content = r#"# Week 1 Plan

Meal plan for ISO 8601 week 1.

Week: 1
Year: 2024
Days: 1, 2, 3, 4, 5, 6, 7
Recipe UUIDs: 9811d359-25fb-4cff-baf1-c78cd3243033, 4a604773-ec4d-47b1-b622-486bf61a878a, 8e3d2386-41ec-4471-9c09-7e794b0dc207, 6a25a017-327c-4c6d-aa91-b7c7268a7f1d, 12f50181-4156-4bee-b72a-7d7e10f19d2f, 8ffb2050-fa21-4827-b5be-664ee1af49d2, 2c14da93-84fd-4044-abf4-8dd83babec4c

## Recipe Days

This week's meal plan uses the following day-of-year recipes (Monday through Sunday):

- Monday: Day 1
- Tuesday: Day 2
- Wednesday: Day 3
"#;

        let plan = EmbeddedPlanStore::parse_plan_markdown(content, 1).unwrap();
        let recipe_store = EmbeddedRecipeStore::global();

        assert_eq!(plan.week, 1);
        assert_eq!(plan.recipe_uuids.len(), 7);

        // Verify UUIDs match the recipes for days 1-7
        for (i, day) in (1..=7).enumerate() {
            let day_id = format!("day-{}", day);
            let recipe = recipe_store.get_by_id(&day_id).unwrap();
            assert_eq!(plan.recipe_uuids[i], recipe.uuid);
        }
    }

    #[test]
    fn test_extract_recipe_uuids() {
        let content = "Week: 1\nRecipe UUIDs: 9811d359-25fb-4cff-baf1-c78cd3243033, 4a604773-ec4d-47b1-b622-486bf61a878a\n";
        let uuids = EmbeddedPlanStore::extract_recipe_uuids(content).unwrap();
        assert_eq!(uuids.len(), 2);
        assert_eq!(uuids[0].to_string(), "9811d359-25fb-4cff-baf1-c78cd3243033");
        assert_eq!(uuids[1].to_string(), "4a604773-ec4d-47b1-b622-486bf61a878a");
    }

    #[test]
    fn test_extract_recipe_uuids_missing() {
        let content = "Week: 5\nNo Recipe UUIDs field here\n";
        let result = EmbeddedPlanStore::extract_recipe_uuids(content);
        assert!(result.is_err());
    }

    #[test]
    fn test_extract_recipe_uuids_invalid_format() {
        let content = "Recipe UUIDs: not-a-uuid, also-not-a-uuid\n";
        let result = EmbeddedPlanStore::extract_recipe_uuids(content);
        assert!(result.is_err());
    }
}
