#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../content");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR environment variable not set");

    // Generate embedded_recipes.rs
    let dest_path = Path::new(&out_dir).join("embedded_recipes.rs");
    let mut f = fs::File::create(&dest_path).expect("Failed to create embedded_recipes.rs");

    // Generate the vector of recipe files
    writeln!(f, "// Auto-generated by build.rs - do not edit manually")
        .expect("Failed to write to embedded_recipes.rs");
    writeln!(f, "vec![").expect("Failed to write to embedded_recipes.rs");

    // Generate entries for day-1 through day-365
    for day in 1..=365 {
        writeln!(
            f,
            "    ({}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../content/day-{}.md\"))),",
            day, day
        )
        .expect("Failed to write to embedded_recipes.rs");
    }

    writeln!(f, "]").expect("Failed to write to embedded_recipes.rs");

    // Generate embedded_plans.rs
    let dest_path = Path::new(&out_dir).join("embedded_plans.rs");
    let mut f = fs::File::create(&dest_path).expect("Failed to create embedded_plans.rs");

    // Generate the vector of plan files
    writeln!(f, "// Auto-generated by build.rs - do not edit manually")
        .expect("Failed to write to embedded_plans.rs");
    writeln!(f, "vec![").expect("Failed to write to embedded_plans.rs");

    // Generate entries for week-1 through week-53
    for week in 1..=53 {
        writeln!(
            f,
            "    ({}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../content/week-{}.md\"))),",
            week, week
        )
        .expect("Failed to write to embedded_plans.rs");
    }

    writeln!(f, "]").expect("Failed to write to embedded_plans.rs");
}
