[package]
name = "web"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
dioxus = { workspace = true, features = ["web", "router"] }
auth_sdk = { workspace = true }
chrono = { workspace = true }
cookbook-core = { path = "../core" }
cookbook-data-md = { path = "../data_md" }
web-sys = "0.3.83"
uuid = { version = "1.19", features = ["v4", "js"] }

[features]
default = ["web"]
web = []

[package.metadata.cast]
exemplar = true
project_type = "static_website"
framework = "dioxus"
deploys = ["../cloudflare"]
