---
name: CD

'on':
  push:
    branches:
      - main
    paths:
      - '**/artifacts/x86_64-unknown-linux-gnu/**'

permissions:
  contents: read

jobs:
  run-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Run CD on new artifacts
        run: |
          cargo install --path ./cast/cast_cli
          cast cd --last-commit --recursive 2
